### ISSUE TITLE
F-Droid requirements

### ISSUE THREAD

**Issue by casimir** [casimir/frigoligo#170]
F-Droid has a a list of requirements. Some are good for the project in the long term, some are just requirements.

- [x] `fastlane` in root directory → #173
- [x] Keep screenshots in git repo → #173
- [x] Maintain changelogs in `fastlane` metadata (difficult with the current release workflow) → manual
- [x] Use a pinned version of Flutter in CI → ~#175~ #177
- [x] Build `isar` from source using git submodule #178 
- [x] Bundle Google Fonts → #172 

Merge Request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14933
